// Code generated by fastssz. DO NOT EDIT.
// Hash: 2f92f54a514c7804b1c1efeb3ee2858d6518babaa6f78859b87690a21850994c
// Version: 0.1.3
package capella

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Attestation object
func (a *Attestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the Attestation object to a target array
func (a *Attestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(136)

	// Offset (0) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.AggregationBits)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if dst, err = a.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (2) 'Signatures'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'AggregationBits'
	if size := len(a.AggregationBits); size > 128 {
		err = ssz.ErrBytesLengthFn("Attestation.AggregationBits", size, 128)
		return
	}
	dst = append(dst, a.AggregationBits...)

	// Field (2) 'Signatures'
	if size := len(a.Signatures); size > 128 {
		err = ssz.ErrListTooBigFn("Attestation.Signatures", size, 128)
		return
	}
	for ii := 0; ii < len(a.Signatures); ii++ {
		dst = append(dst, a.Signatures[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Attestation object
func (a *Attestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 136 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 136 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.UnmarshalSSZ(buf[4:132]); err != nil {
		return err
	}

	// Offset (2) 'Signatures'
	if o2 = ssz.ReadOffset(buf[132:136]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (0) 'AggregationBits'
	{
		buf = tail[o0:o2]
		if err = ssz.ValidateBitlist(buf, 128); err != nil {
			return err
		}
		if cap(a.AggregationBits) == 0 {
			a.AggregationBits = make([]byte, 0, len(buf))
		}
		a.AggregationBits = append(a.AggregationBits, buf...)
	}

	// Field (2) 'Signatures'
	{
		buf = tail[o2:]
		num, err := ssz.DivideInt2(len(buf), 4627, 128)
		if err != nil {
			return err
		}
		a.Signatures = make([]MLDSA87Signature, num)
		for ii := 0; ii < num; ii++ {
			copy(a.Signatures[ii][:], buf[ii*4627:(ii+1)*4627])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Attestation object
func (a *Attestation) SizeSSZ() (size int) {
	size = 136

	// Field (0) 'AggregationBits'
	size += len(a.AggregationBits)

	// Field (2) 'Signatures'
	size += len(a.Signatures) * 4627

	return
}

// HashTreeRoot ssz hashes the Attestation object
func (a *Attestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the Attestation object with a hasher
func (a *Attestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AggregationBits'
	if len(a.AggregationBits) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(a.AggregationBits, 128)

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Signatures'
	{
		if size := len(a.Signatures); size > 128 {
			err = ssz.ErrListTooBigFn("Attestation.Signatures", size, 128)
			return
		}
		subIndx := hh.Index()
		for _, i := range a.Signatures {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(a.Signatures))
		hh.MerkleizeWithMixin(subIndx, numItems, 128)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Attestation object
func (a *Attestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}
