// Code generated by fastssz. DO NOT EDIT.
// Hash: 2f92f54a514c7804b1c1efeb3ee2858d6518babaa6f78859b87690a21850994c
// Version: 0.1.3
package capella

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the IndexedAttestation object
func (i *IndexedAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(i)
}

// MarshalSSZTo ssz marshals the IndexedAttestation object to a target array
func (i *IndexedAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(136)

	// Offset (0) 'AttestingIndices'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(i.AttestingIndices) * 8

	// Field (1) 'Data'
	if i.Data == nil {
		i.Data = new(AttestationData)
	}
	if dst, err = i.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (2) 'Signatures'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'AttestingIndices'
	if size := len(i.AttestingIndices); size > 128 {
		err = ssz.ErrListTooBigFn("IndexedAttestation.AttestingIndices", size, 128)
		return
	}
	for ii := 0; ii < len(i.AttestingIndices); ii++ {
		dst = ssz.MarshalUint64(dst, i.AttestingIndices[ii])
	}

	// Field (2) 'Signatures'
	if size := len(i.Signatures); size > 128 {
		err = ssz.ErrListTooBigFn("IndexedAttestation.Signatures", size, 128)
		return
	}
	for ii := 0; ii < len(i.Signatures); ii++ {
		dst = append(dst, i.Signatures[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the IndexedAttestation object
func (i *IndexedAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 136 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2 uint64

	// Offset (0) 'AttestingIndices'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 136 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Data'
	if i.Data == nil {
		i.Data = new(AttestationData)
	}
	if err = i.Data.UnmarshalSSZ(buf[4:132]); err != nil {
		return err
	}

	// Offset (2) 'Signatures'
	if o2 = ssz.ReadOffset(buf[132:136]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (0) 'AttestingIndices'
	{
		buf = tail[o0:o2]
		num, err := ssz.DivideInt2(len(buf), 8, 128)
		if err != nil {
			return err
		}
		i.AttestingIndices = ssz.ExtendUint64(i.AttestingIndices, num)
		for ii := 0; ii < num; ii++ {
			i.AttestingIndices[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (2) 'Signatures'
	{
		buf = tail[o2:]
		num, err := ssz.DivideInt2(len(buf), 4627, 128)
		if err != nil {
			return err
		}
		i.Signatures = make([]MLDSA87Signature, num)
		for ii := 0; ii < num; ii++ {
			copy(i.Signatures[ii][:], buf[ii*4627:(ii+1)*4627])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the IndexedAttestation object
func (i *IndexedAttestation) SizeSSZ() (size int) {
	size = 136

	// Field (0) 'AttestingIndices'
	size += len(i.AttestingIndices) * 8

	// Field (2) 'Signatures'
	size += len(i.Signatures) * 4627

	return
}

// HashTreeRoot ssz hashes the IndexedAttestation object
func (i *IndexedAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(i)
}

// HashTreeRootWith ssz hashes the IndexedAttestation object with a hasher
func (i *IndexedAttestation) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'AttestingIndices'
	{
		if size := len(i.AttestingIndices); size > 128 {
			err = ssz.ErrListTooBigFn("IndexedAttestation.AttestingIndices", size, 128)
			return
		}
		subIndx := hh.Index()
		for _, i := range i.AttestingIndices {
			hh.AppendUint64(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(i.AttestingIndices))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(128, numItems, 8))
	}

	// Field (1) 'Data'
	if i.Data == nil {
		i.Data = new(AttestationData)
	}
	if err = i.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'Signatures'
	{
		if size := len(i.Signatures); size > 128 {
			err = ssz.ErrListTooBigFn("IndexedAttestation.Signatures", size, 128)
			return
		}
		subIndx := hh.Index()
		for _, i := range i.Signatures {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(i.Signatures))
		hh.MerkleizeWithMixin(subIndx, numItems, 128)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the IndexedAttestation object
func (i *IndexedAttestation) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(i)
}
