// Code generated by fastssz. DO NOT EDIT.
// Hash: 2f92f54a514c7804b1c1efeb3ee2858d6518babaa6f78859b87690a21850994c
// Version: 0.1.3
package capella

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SyncCommitteeContribution object
func (s *SyncCommitteeContribution) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SyncCommitteeContribution object to a target array
func (s *SyncCommitteeContribution) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(54)

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(s.Slot))

	// Field (1) 'BeaconBlockRoot'
	dst = append(dst, s.BeaconBlockRoot[:]...)

	// Field (2) 'SubcommitteeIndex'
	dst = ssz.MarshalUint64(dst, s.SubcommitteeIndex)

	// Field (3) 'AggregationBits'
	if size := len(s.AggregationBits); size != 2 {
		err = ssz.ErrBytesLengthFn("SyncCommitteeContribution.AggregationBits", size, 2)
		return
	}
	dst = append(dst, s.AggregationBits...)

	// Offset (4) 'Signatures'
	dst = ssz.WriteOffset(dst, offset)

	// Field (4) 'Signatures'
	if size := len(s.Signatures); size > 16 {
		err = ssz.ErrListTooBigFn("SyncCommitteeContribution.Signatures", size, 16)
		return
	}
	for ii := 0; ii < len(s.Signatures); ii++ {
		dst = append(dst, s.Signatures[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SyncCommitteeContribution object
func (s *SyncCommitteeContribution) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 54 {
		return ssz.ErrSize
	}

	tail := buf
	var o4 uint64

	// Field (0) 'Slot'
	s.Slot = Slot(ssz.UnmarshallUint64(buf[0:8]))

	// Field (1) 'BeaconBlockRoot'
	copy(s.BeaconBlockRoot[:], buf[8:40])

	// Field (2) 'SubcommitteeIndex'
	s.SubcommitteeIndex = ssz.UnmarshallUint64(buf[40:48])

	// Field (3) 'AggregationBits'
	if cap(s.AggregationBits) == 0 {
		s.AggregationBits = make([]byte, 0, len(buf[48:50]))
	}
	s.AggregationBits = append(s.AggregationBits, buf[48:50]...)

	// Offset (4) 'Signatures'
	if o4 = ssz.ReadOffset(buf[50:54]); o4 > size {
		return ssz.ErrOffset
	}

	if o4 != 54 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (4) 'Signatures'
	{
		buf = tail[o4:]
		num, err := ssz.DivideInt2(len(buf), 4627, 16)
		if err != nil {
			return err
		}
		s.Signatures = make([]MLDSA87Signature, num)
		for ii := 0; ii < num; ii++ {
			copy(s.Signatures[ii][:], buf[ii*4627:(ii+1)*4627])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SyncCommitteeContribution object
func (s *SyncCommitteeContribution) SizeSSZ() (size int) {
	size = 54

	// Field (4) 'Signatures'
	size += len(s.Signatures) * 4627

	return
}

// HashTreeRoot ssz hashes the SyncCommitteeContribution object
func (s *SyncCommitteeContribution) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SyncCommitteeContribution object with a hasher
func (s *SyncCommitteeContribution) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(uint64(s.Slot))

	// Field (1) 'BeaconBlockRoot'
	hh.PutBytes(s.BeaconBlockRoot[:])

	// Field (2) 'SubcommitteeIndex'
	hh.PutUint64(s.SubcommitteeIndex)

	// Field (3) 'AggregationBits'
	if size := len(s.AggregationBits); size != 2 {
		err = ssz.ErrBytesLengthFn("SyncCommitteeContribution.AggregationBits", size, 2)
		return
	}
	hh.PutBytes(s.AggregationBits)

	// Field (4) 'Signatures'
	{
		if size := len(s.Signatures); size > 16 {
			err = ssz.ErrListTooBigFn("SyncCommitteeContribution.Signatures", size, 16)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.Signatures {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(s.Signatures))
		hh.MerkleizeWithMixin(subIndx, numItems, 16)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SyncCommitteeContribution object
func (s *SyncCommitteeContribution) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
