// Code generated by fastssz. DO NOT EDIT.
// Hash: 2f92f54a514c7804b1c1efeb3ee2858d6518babaa6f78859b87690a21850994c
// Version: 0.1.3
package capella

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SyncAggregate object
func (s *SyncAggregate) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SyncAggregate object to a target array
func (s *SyncAggregate) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(6)

	// Field (0) 'SyncCommitteeBits'
	if size := len(s.SyncCommitteeBits); size != 2 {
		err = ssz.ErrBytesLengthFn("SyncAggregate.SyncCommitteeBits", size, 2)
		return
	}
	dst = append(dst, s.SyncCommitteeBits...)

	// Offset (1) 'SyncCommitteeSignatures'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'SyncCommitteeSignatures'
	if size := len(s.SyncCommitteeSignatures); size > 16 {
		err = ssz.ErrListTooBigFn("SyncAggregate.SyncCommitteeSignatures", size, 16)
		return
	}
	for ii := 0; ii < len(s.SyncCommitteeSignatures); ii++ {
		dst = append(dst, s.SyncCommitteeSignatures[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SyncAggregate object
func (s *SyncAggregate) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 6 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'SyncCommitteeBits'
	if cap(s.SyncCommitteeBits) == 0 {
		s.SyncCommitteeBits = make([]byte, 0, len(buf[0:2]))
	}
	s.SyncCommitteeBits = append(s.SyncCommitteeBits, buf[0:2]...)

	// Offset (1) 'SyncCommitteeSignatures'
	if o1 = ssz.ReadOffset(buf[2:6]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 6 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'SyncCommitteeSignatures'
	{
		buf = tail[o1:]
		num, err := ssz.DivideInt2(len(buf), 4627, 16)
		if err != nil {
			return err
		}
		s.SyncCommitteeSignatures = make([]MLDSA87Signature, num)
		for ii := 0; ii < num; ii++ {
			copy(s.SyncCommitteeSignatures[ii][:], buf[ii*4627:(ii+1)*4627])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SyncAggregate object
func (s *SyncAggregate) SizeSSZ() (size int) {
	size = 6

	// Field (1) 'SyncCommitteeSignatures'
	size += len(s.SyncCommitteeSignatures) * 4627

	return
}

// HashTreeRoot ssz hashes the SyncAggregate object
func (s *SyncAggregate) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SyncAggregate object with a hasher
func (s *SyncAggregate) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'SyncCommitteeBits'
	if size := len(s.SyncCommitteeBits); size != 2 {
		err = ssz.ErrBytesLengthFn("SyncAggregate.SyncCommitteeBits", size, 2)
		return
	}
	hh.PutBytes(s.SyncCommitteeBits)

	// Field (1) 'SyncCommitteeSignatures'
	{
		if size := len(s.SyncCommitteeSignatures); size > 16 {
			err = ssz.ErrListTooBigFn("SyncAggregate.SyncCommitteeSignatures", size, 16)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.SyncCommitteeSignatures {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(s.SyncCommitteeSignatures))
		hh.MerkleizeWithMixin(subIndx, numItems, 16)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SyncAggregate object
func (s *SyncAggregate) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
