// Code generated by fastssz. DO NOT EDIT.
// Hash: 50c109e1f6574700d1bbe3c5483093a30dafc1ec8ca61860481e73ee85212cd2
// Version: 0.1.3
package api

import (
	ssz "github.com/ferranbt/fastssz"
	apiv1 "github.com/theQRL/qrl-metrics-exporter/pkg/go-consensus-client/api/v1"
	"github.com/theQRL/qrl-metrics-exporter/pkg/go-consensus-client/spec"
)

// MarshalSSZ ssz marshals the VersionedSignedValidatorRegistration object
func (v *VersionedSignedValidatorRegistration) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the VersionedSignedValidatorRegistration object to a target array
func (v *VersionedSignedValidatorRegistration) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Version'
	dst = ssz.MarshalUint64(dst, uint64(v.Version))

	// Field (1) 'V1'
	if v.V1 == nil {
		v.V1 = new(apiv1.SignedValidatorRegistration)
	}
	if dst, err = v.V1.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the VersionedSignedValidatorRegistration object
func (v *VersionedSignedValidatorRegistration) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 7263 {
		return ssz.ErrSize
	}

	// Field (0) 'Version'
	v.Version = spec.BuilderVersion(ssz.UnmarshallUint64(buf[0:8]))

	// Field (1) 'V1'
	if v.V1 == nil {
		v.V1 = new(apiv1.SignedValidatorRegistration)
	}
	if err = v.V1.UnmarshalSSZ(buf[8:7263]); err != nil {
		return err
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the VersionedSignedValidatorRegistration object
func (v *VersionedSignedValidatorRegistration) SizeSSZ() (size int) {
	size = 7263
	return
}

// HashTreeRoot ssz hashes the VersionedSignedValidatorRegistration object
func (v *VersionedSignedValidatorRegistration) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the VersionedSignedValidatorRegistration object with a hasher
func (v *VersionedSignedValidatorRegistration) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Version'
	hh.PutUint64(uint64(v.Version))

	// Field (1) 'V1'
	if v.V1 == nil {
		v.V1 = new(apiv1.SignedValidatorRegistration)
	}
	if err = v.V1.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the VersionedSignedValidatorRegistration object
func (v *VersionedSignedValidatorRegistration) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}
