// Code generated by fastssz. DO NOT EDIT.
// Hash: 50c109e1f6574700d1bbe3c5483093a30dafc1ec8ca61860481e73ee85212cd2
// Version: 0.1.3
package api

import (
	ssz "github.com/ferranbt/fastssz"
	apiv1capella "github.com/theQRL/qrl-metrics-exporter/pkg/go-consensus-client/api/v1/capella"
	"github.com/theQRL/qrl-metrics-exporter/pkg/go-consensus-client/spec"
)

// MarshalSSZ ssz marshals the VersionedBlindedBeaconBlock object
func (v *VersionedBlindedBeaconBlock) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the VersionedBlindedBeaconBlock object to a target array
func (v *VersionedBlindedBeaconBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Field (0) 'Version'
	dst = ssz.MarshalUint64(dst, uint64(v.Version))

	// Offset (1) 'Capella'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Capella'
	if dst, err = v.Capella.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the VersionedBlindedBeaconBlock object
func (v *VersionedBlindedBeaconBlock) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Version'
	v.Version = spec.DataVersion(ssz.UnmarshallUint64(buf[0:8]))

	// Offset (1) 'Capella'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Capella'
	{
		buf = tail[o1:]
		if v.Capella == nil {
			v.Capella = new(apiv1capella.BlindedBeaconBlock)
		}
		if err = v.Capella.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the VersionedBlindedBeaconBlock object
func (v *VersionedBlindedBeaconBlock) SizeSSZ() (size int) {
	size = 12

	// Field (1) 'Capella'
	if v.Capella == nil {
		v.Capella = new(apiv1capella.BlindedBeaconBlock)
	}
	size += v.Capella.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the VersionedBlindedBeaconBlock object
func (v *VersionedBlindedBeaconBlock) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the VersionedBlindedBeaconBlock object with a hasher
func (v *VersionedBlindedBeaconBlock) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Version'
	hh.PutUint64(uint64(v.Version))

	// Field (1) 'Capella'
	if err = v.Capella.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the VersionedBlindedBeaconBlock object
func (v *VersionedBlindedBeaconBlock) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}
