// Code generated by fastssz. DO NOT EDIT.
// Hash: e371ee6f21c994d503a1000c053237f74da44138364110925fe5acc0b1ffe3cd
// Version: 0.1.3
package api

import (
	ssz "github.com/ferranbt/fastssz"
	apiv1capella "github.com/theQRL/qrl-metrics-exporter/pkg/go-consensus-client/api/v1/capella"
	"github.com/theQRL/qrl-metrics-exporter/pkg/go-consensus-client/spec"
)

// MarshalSSZ ssz marshals the VersionedSignedBlindedBeaconBlock object
func (v *VersionedSignedBlindedBeaconBlock) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the VersionedSignedBlindedBeaconBlock object to a target array
func (v *VersionedSignedBlindedBeaconBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(28)

	// Field (0) 'Version'
	dst = ssz.MarshalUint64(dst, uint64(v.Version))

	// Offset (2) 'Capella'
	dst = ssz.WriteOffset(dst, offset)
	if v.Capella == nil {
		v.Capella = new(apiv1capella.SignedBlindedBeaconBlock)
	}
	offset += v.Capella.SizeSSZ()

	// Field (2) 'Capella'
	if dst, err = v.Capella.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the VersionedSignedBlindedBeaconBlock object
func (v *VersionedSignedBlindedBeaconBlock) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 28 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2, o3 uint64

	// Field (0) 'Version'
	v.Version = spec.DataVersion(ssz.UnmarshallUint64(buf[0:8]))

	// Offset (2) 'Capella'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (2) 'Capella'
	{
		buf = tail[o2:o3]
		if v.Capella == nil {
			v.Capella = new(apiv1capella.SignedBlindedBeaconBlock)
		}
		if err = v.Capella.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the VersionedSignedBlindedBeaconBlock object
func (v *VersionedSignedBlindedBeaconBlock) SizeSSZ() (size int) {
	size = 28

	// Field (2) 'Capella'
	if v.Capella == nil {
		v.Capella = new(apiv1capella.SignedBlindedBeaconBlock)
	}
	size += v.Capella.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the VersionedSignedBlindedBeaconBlock object
func (v *VersionedSignedBlindedBeaconBlock) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the VersionedSignedBlindedBeaconBlock object with a hasher
func (v *VersionedSignedBlindedBeaconBlock) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Version'
	hh.PutUint64(uint64(v.Version))

	// Field (2) 'Capella'
	if err = v.Capella.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the VersionedSignedBlindedBeaconBlock object
func (v *VersionedSignedBlindedBeaconBlock) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}
